// Run this as a script macro in a world to set up the barbrawl defaults for that world, reset all actors' bars to that and set all places tokens to the new bars.
const mechBars = {
    bar1: {
        order: 0,
        id: "bar1",
        attribute: "heat",
        mincolor: "#873b3b",
        maxcolor: "#FF0000",
        position: "top-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: 30,
        indentRight: null,
        shareHeight: true,
        style: "fraction",
        label: "HEAT",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    hp: {
        order: 2,
        id: "bar3",
        attribute: "hp",
        mincolor: "#FF0000",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: 30,
        indentRight: null,
        shareHeight: true,
        style: "fraction",
        label: "HP",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    bar2: {
        order: 1,
        id: "bar2",
        attribute: "stress",
        mincolor: "#FF0000",
        maxcolor: "#FF0000",
        position: "top-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: 70,
        shareHeight: false,
        style: "none",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: 4,
        subdivisionsOwner: true,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    structure: {
        order: 3,
        id: "bar4",
        attribute: "structure",
        mincolor: "#80FF00",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: 70,
        shareHeight: false,
        style: "none",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: 4,
        subdivisionsOwner: true,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    burn: {
        order: 5,
        id: "bar6",
        attribute: "burn",
        mincolor: "#ffa200",
        maxcolor: "#ffa200",
        position: "bottom-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "none",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    overshield: {
        order: 4,
        id: "bar5",
        attribute: "overshield",
        mincolor: "#0040ff",
        maxcolor: "#0040ff",
        position: "bottom-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "none",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
};

const npcBars = {
    bar1: {
        order: 0,
        id: "bar1",
        attribute: "heat",
        mincolor: "#873b3b",
        maxcolor: "#FF0000",
        position: "top-outer",
        otherVisibility: 0,
        ownerVisibility: 30,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: 30,
        indentRight: null,
        shareHeight: true,
        style: "fraction",
        label: "HEAT",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    bar2: {
        order: 1,
        id: "bar2",
        attribute: "stress",
        mincolor: "#FF0000",
        maxcolor: "#FF0000",
        position: "top-outer",
        otherVisibility: 0,
        ownerVisibility: 30,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: 70,
        shareHeight: false,
        style: "none",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: 1,
        subdivisionsOwner: true,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    ownedHp: {
        order: 2,
        id: "bar3",
        attribute: "hp",
        mincolor: "#FF0000",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 0,
        ownerVisibility: 30,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: 30,
        indentRight: null,
        shareHeight: true,
        style: "fraction",
        label: "HP",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    ownedStructure: {
        order: 3,
        id: "bar4",
        attribute: "structure",
        mincolor: "#80FF00",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 0,
        ownerVisibility: 30,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: 70,
        shareHeight: false,
        style: "none",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: 1,
        subdivisionsOwner: true,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    unownedHeat: {
        order: 4,
        id: "bar5",
        attribute: "heat",
        mincolor: "#873b3b",
        maxcolor: "#FF0000",
        position: "top-outer",
        otherVisibility: 30,
        ownerVisibility: 0,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: 30,
        indentRight: null,
        shareHeight: true,
        style: "none",
        label: "HEAT",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    unownedStress: {
        order: 5,
        id: "bar6",
        attribute: "stress",
        mincolor: "#FF0000",
        maxcolor: "#FF0000",
        position: "top-outer",
        otherVisibility: 30,
        ownerVisibility: 0,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: 70,
        shareHeight: false,
        style: "none",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: 1,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    unownedHp: {
        order: 6,
        id: "bar7",
        attribute: "hp",
        mincolor: "#FF0000",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 30,
        ownerVisibility: 0,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: 30,
        indentRight: null,
        shareHeight: true,
        style: "none",
        label: "HP",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    unownedStructure: {
        order: 7,
        id: "bar8",
        attribute: "structure",
        mincolor: "#80FF00",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 30,
        ownerVisibility: 0,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: 70,
        shareHeight: false,
        style: "none",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: 1,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    burn: {
        order: 9,
        id: "bar10",
        attribute: "burn",
        mincolor: "#ffa200",
        maxcolor: "#ffa200",
        position: "bottom-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "user",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    overshield: {
        order: 8,
        id: "bar9",
        attribute: "overshield",
        mincolor: "#0040ff",
        maxcolor: "#0040ff",
        position: "bottom-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "user",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
};

const pilotBars = {
    bar1: {
        order: 0,
        id: "bar1",
        attribute: "hp",
        mincolor: "#FF0000",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: true,
        style: "fraction",
        label: "HP",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    bar2: {
        order: 1,
        id: "bar2",
        attribute: "bond_state.stress",
        mincolor: "#80FF00",
        maxcolor: "#FF0000",
        position: "top-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "fraction",
        label: "STRESS",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    burn: {
        order: 3,
        id: "bar4",
        attribute: "burn",
        mincolor: "#ffa200",
        maxcolor: "#ffa200",
        position: "bottom-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "user",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    overshield: {
        order: 2,
        id: "bar3",
        attribute: "overshield",
        mincolor: "#0040ff",
        maxcolor: "#0040ff",
        position: "bottom-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "user",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
};

const deployableBars = {
    bar1: {
        order: 0,
        id: "bar1",
        attribute: "hp",
        mincolor: "#FF0000",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 0,
        ownerVisibility: 30,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: null,
        shareHeight: true,
        style: "fraction",
        label: "HP",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    bar2: {
        order: 1,
        id: "bar2",
        attribute: "hp",
        mincolor: "#FF0000",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 30,
        ownerVisibility: 0,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "none",
        label: "HP",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    burn: {
        order: 3,
        id: "bar4",
        attribute: "burn",
        mincolor: "#ffa200",
        maxcolor: "#ffa200",
        position: "bottom-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "user",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    overshield: {
        order: 2,
        id: "bar3",
        attribute: "overshield",
        mincolor: "#0040ff",
        maxcolor: "#0040ff",
        position: "bottom-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "user",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
};

const barConfig = game.settings.get("barbrawl", "defaultTypeResources") ?? {};
barConfig['mech'] = mechBars;
barConfig['npc'] = npcBars;
barConfig['pilot'] = pilotBars;
barConfig['deployable'] = deployableBars;

await game.settings.set("barbrawl", "defaultTypeResources", barConfig);

// Reset the bars on all existing actor Prototype Tokens
await Promise.all(
  game.actors.map(a => {
    let barSettings;
    switch (a.type) {
      case 'npc':
        barSettings = npcBars;
        break;
      case 'pilot':
        barSettings = pilotBars;
        break;
      case 'deployable':
        barSettings = deployableBars;
        break;
      default:
        barSettings = mechBars;
        break;
    }

    let target;
    const v = game.version
    if (v < "12" && v >= "11") {
      target = a
    } else if (v >= "12") {
      target = a.prototypeToken
    }
    // Get existing flags to preserve them
    const existingFlags = target.flags || {};

    // Update the actor while preserving the flags
    return target.update({
      flags: {
        ...existingFlags, // Merge existing flags
        barbrawl: {
          ...existingFlags.barbrawl,
          resourceBars: barSettings
        }
      }
    }, { 'diff': false, 'recursive': false });
  })
);

ui.notifications.info("PrototypeToken bar resources updated!");

// Reset the bars on all existing tokens
await Promise.all(
  game.scenes.map(s => {
    const updates = s.tokens.filter(t => t.actor).map(t => {
      let barSettings;

      // Determine which bar settings to use based on token's actor type
      switch (t.actor.type) {
        case 'npc':
          barSettings = npcBars;
          break;
        case 'pilot':
          barSettings = pilotBars;
          break;
        case 'deployable':
          barSettings = deployableBars;
          break;
        default:
          barSettings = mechBars; // Use mechBars by default
          break;
      }

      return {
        _id: t.id,
        flags: {
          ...t.flags, // Preserve existing token flags
          barbrawl: {
            ...t.flags?.barbrawl,
            resourceBars: barSettings
          }
        }
      };
    });
    
    return s.updateEmbeddedDocuments("Token", updates, { 'diff': false, 'recursive': false });
  })
);

ui.notifications.info("Token bar resources updated!");