const RESET = false;
const ACTIVE_SCENE_ONLY = false;

const mechBars = {
    bar1: {
        order: 0,
        id: "bar1",
        attribute: "heat",
        mincolor: "#873b3b",
        maxcolor: "#FF0000",
        position: "top-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: 30,
        indentRight: null,
        shareHeight: true,
        style: "fraction",
        label: "HEAT",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    hp: {
        order: 2,
        id: "bar3",
        attribute: "hp",
        mincolor: "#FF0000",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: 30,
        indentRight: null,
        shareHeight: true,
        style: "fraction",
        label: "HP",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    bar2: {
        order: 1,
        id: "bar2",
        attribute: "stress",
        mincolor: "#FF0000",
        maxcolor: "#FF0000",
        position: "top-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: 70,
        shareHeight: false,
        style: "none",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: 4,
        subdivisionsOwner: true,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    structure: {
        order: 3,
        id: "bar4",
        attribute: "structure",
        mincolor: "#80FF00",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: 70,
        shareHeight: false,
        style: "none",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: 4,
        subdivisionsOwner: true,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    burn: {
        order: 5,
        id: "bar6",
        attribute: "burn",
        mincolor: "#ffa200",
        maxcolor: "#ffa200",
        position: "bottom-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "none",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    overshield: {
        order: 4,
        id: "bar5",
        attribute: "overshield",
        mincolor: "#0040ff",
        maxcolor: "#0040ff",
        position: "bottom-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "none",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
};

const npcBars = {
    bar1: {
        order: 0,
        id: "bar1",
        attribute: "heat",
        mincolor: "#873b3b",
        maxcolor: "#FF0000",
        position: "top-outer",
        otherVisibility: 0,
        ownerVisibility: 30,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: 30,
        indentRight: null,
        shareHeight: true,
        style: "fraction",
        label: "HEAT",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    bar2: {
        order: 1,
        id: "bar2",
        attribute: "stress",
        mincolor: "#FF0000",
        maxcolor: "#FF0000",
        position: "top-outer",
        otherVisibility: 0,
        ownerVisibility: 30,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: 70,
        shareHeight: false,
        style: "none",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: 1,
        subdivisionsOwner: true,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    ownedHp: {
        order: 2,
        id: "bar3",
        attribute: "hp",
        mincolor: "#FF0000",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 0,
        ownerVisibility: 30,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: 30,
        indentRight: null,
        shareHeight: true,
        style: "fraction",
        label: "HP",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    ownedStructure: {
        order: 3,
        id: "bar4",
        attribute: "structure",
        mincolor: "#80FF00",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 0,
        ownerVisibility: 30,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: 70,
        shareHeight: false,
        style: "none",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: 1,
        subdivisionsOwner: true,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    unownedHeat: {
        order: 4,
        id: "bar5",
        attribute: "heat",
        mincolor: "#873b3b",
        maxcolor: "#FF0000",
        position: "top-outer",
        otherVisibility: 30,
        ownerVisibility: 0,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: 30,
        indentRight: null,
        shareHeight: true,
        style: "none",
        label: "HEAT",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    unownedStress: {
        order: 5,
        id: "bar6",
        attribute: "stress",
        mincolor: "#FF0000",
        maxcolor: "#FF0000",
        position: "top-outer",
        otherVisibility: 30,
        ownerVisibility: 0,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: 70,
        shareHeight: false,
        style: "none",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: 1,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    unownedHp: {
        order: 6,
        id: "bar7",
        attribute: "hp",
        mincolor: "#FF0000",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 30,
        ownerVisibility: 0,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: 30,
        indentRight: null,
        shareHeight: true,
        style: "none",
        label: "HP",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    unownedStructure: {
        order: 7,
        id: "bar8",
        attribute: "structure",
        mincolor: "#80FF00",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 30,
        ownerVisibility: 0,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: 70,
        shareHeight: false,
        style: "none",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: 1,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    burn: {
        order: 9,
        id: "bar10",
        attribute: "burn",
        mincolor: "#ffa200",
        maxcolor: "#ffa200",
        position: "bottom-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "user",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    overshield: {
        order: 8,
        id: "bar9",
        attribute: "overshield",
        mincolor: "#0040ff",
        maxcolor: "#0040ff",
        position: "bottom-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "user",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
};

const pilotBars = {
    bar1: {
        order: 0,
        id: "bar1",
        attribute: "hp",
        mincolor: "#FF0000",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: true,
        style: "fraction",
        label: "HP",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    bar2: {
        order: 1,
        id: "bar2",
        attribute: "bond_state.stress",
        mincolor: "#80FF00",
        maxcolor: "#FF0000",
        position: "top-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "fraction",
        label: "STRESS",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    burn: {
        order: 3,
        id: "bar4",
        attribute: "burn",
        mincolor: "#ffa200",
        maxcolor: "#ffa200",
        position: "bottom-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "user",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    overshield: {
        order: 2,
        id: "bar3",
        attribute: "overshield",
        mincolor: "#0040ff",
        maxcolor: "#0040ff",
        position: "bottom-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "user",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
};

const deployableBars = {
    bar1: {
        order: 0,
        id: "bar1",
        attribute: "hp",
        mincolor: "#FF0000",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 0,
        ownerVisibility: 30,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: null,
        shareHeight: true,
        style: "fraction",
        label: "HP",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    bar2: {
        order: 1,
        id: "bar2",
        attribute: "hp",
        mincolor: "#FF0000",
        maxcolor: "#80FF00",
        position: "top-outer",
        otherVisibility: 30,
        ownerVisibility: 0,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: false,
        hideNoCombat: false,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "none",
        label: "HP",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    burn: {
        order: 3,
        id: "bar4",
        attribute: "burn",
        mincolor: "#ffa200",
        maxcolor: "#ffa200",
        position: "bottom-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "user",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
    overshield: {
        order: 2,
        id: "bar3",
        attribute: "overshield",
        mincolor: "#0040ff",
        maxcolor: "#0040ff",
        position: "bottom-outer",
        otherVisibility: 50,
        ownerVisibility: 50,
        gmVisibility: -1,
        hideFull: false,
        hideEmpty: false,
        hideCombat: true,
        hideNoCombat: true,
        indentLeft: null,
        indentRight: null,
        shareHeight: false,
        style: "user",
        label: "",
        invert: false,
        invertDirection: false,
        subdivisions: null,
        subdivisionsOwner: false,
        fgImage: "",
        bgImage: "",
        opacity: null,
        hideHud: false
    },
};

function barsForActor(actor) {
    let baseBarSettings = mechBars;

    switch (actor.type) {
    case 'npc': baseBarSettings = npcBars; break;
    case 'pilot': baseBarSettings = pilotBars; break;
    case 'deployable': baseBarSettings = deployableBars; break;
    }

    let barSettings = structuredClone(baseBarSettings);
    if (actor.type === 'npc') {
        const structureMax = actor.system.structure?.max ?? 1;
        const stressMax = actor.system.stress?.max ?? 1;
        barSettings.ownedStructure.subdivisions = structureMax;
        barSettings.unownedStructure.subdivisions = structureMax;
        barSettings.bar2.subdivisions = stressMax;
        barSettings.unownedStress.subdivisions = stressMax;
    }
    return barSettings;
}

function tokenFlagsUpdate(existingFlags, barSettings) {
    const flags = foundry.utils.deepClone(existingFlags) ?? {};
    if (RESET)
        delete flags.barbrawl;
    flags.barbrawl = { ...flags.barbrawl, resourceBars: barSettings };
    return flags;
}

if (!game.user.isGM)
    return;

const barConfig = game.settings.get("barbrawl", "defaultTypeResources") ?? {};
barConfig['mech'] = mechBars;
barConfig['npc'] = npcBars;
barConfig['pilot'] = pilotBars;
barConfig['deployable'] = deployableBars;
await game.settings.set("barbrawl", "defaultTypeResources", barConfig);

ui.notifications.info("Updating Prototype Tokens...");
await Promise.all(
    game.actors.map(async (actor) => {
        await actor.prototypeToken.unsetFlag('barbrawl', 'resourceBars');
        return actor.prototypeToken.setFlag('barbrawl', 'resourceBars', barsForActor(actor));
    })
);
ui.notifications.info("PrototypeToken resources updated!");

ui.notifications.info("Updating placed Tokens in all scenes...");
for (const scene of game.scenes) {
    if (ACTIVE_SCENE_ONLY && scene !== game.canvas.scene)
        continue;
    const updates = scene.tokens.filter(tokenDoc => tokenDoc.actor).map(tokenDoc => {
        return {
            _id: tokenDoc.id,
            flags: tokenFlagsUpdate(tokenDoc.flags, barsForActor(tokenDoc.actor))
        };
    });

    if (updates.length > 0) {
        try {
            await scene.updateEmbeddedDocuments("Token", updates, { 'diff': false, 'recursive': false });
        } catch (err) {
            console.warn(`Lancer BarBrawl Update: Failed to update tokens in scene ${scene.name}`, err);
        }
    }
}
ui.notifications.info("Token resources updated!");